services:
  postgres:
    image: postgres
    container_name: exit-debt-postgres
    restart: unless-stopped
    environment:
      POSTGRES_DB: debt_tracker
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - debt-tracker-network

  localstack:
    image: localstack/localstack:latest
    container_name: exit-debt-localstack
    restart: unless-stopped
    ports:
      - "4566:4566"
    env_file:
      - .env
    volumes:
      - localstack_data:/var/lib/localstack/data
      - /var/run/docker.sock:/var/run/docker.sock
      - ./init_s3.py:/etc/localstack/init/ready.d/init_s3.py
    networks:
      - debt-tracker-network

volumes:
  postgres_data:
    driver: local
  localstack_data:
    driver: local

networks:
  debt-tracker-network:
    driver: bridge
